services:
    # Twig extension
    vince_cms.admin.twig.extension:
        class: Vince\Bundle\CmsSonataAdminBundle\Twig\Extension\CmsSonataAdminExtension
        tags:
            - { name: twig.extension }

    # Admin class
    vince_cms.admin.publishable:
        class: Vince\Bundle\CmsSonataAdminBundle\Admin\Entity\PublishableAdmin
        abstract: true
        calls:
            - [ setTranslationDomain, [ 'SonataAdminBundle' ] ]

    vince_cms.admin.article:
        class: %vince_cms.admin.article%
        parent: vince_cms.admin.publishable
        tags:
            - name: sonata.admin
              manager_type: orm
              group: cms
              label_catalogue: SonataAdminBundle
              label: Articles
        arguments: [ ~, %vince_cms.class.article%, VinceCmsSonataAdminBundle:Publishable ]
        calls:
            - [ setMetaRepository, [ @vince_cms.repository.meta ] ]
            - [ setUser, [ @security.context ] ]
            - [ setDoctrine, [ @doctrine ] ]
            - [ setCacheDir, [ %kernel.cache_dir% ] ]
            - [ setArticleMetaClass, [ %vince_cms.class.articlemeta% ] ]

    vince_cms.admin.block:
        class: %vince_cms.admin.block%
        parent: vince_cms.admin.publishable
        tags:
            - name: sonata.admin
              manager_type: orm
              group: cms
              label_catalogue: SonataAdminBundle
              label: Blocs
        arguments: [ ~, %vince_cms.class.block%, VinceCmsSonataAdminBundle:Publishable ]
        calls:
            - [ setTranslationDomain, [ 'SonataAdminBundle' ] ]

    vince_cms.admin.menu:
        class: %vince_cms.admin.menu%
        parent: vince_cms.admin.publishable
        tags:
            - name: sonata.admin
              manager_type: orm
              group: cms
              label_catalogue: SonataAdminBundle
              label: Menus
        arguments: [ ~, %vince_cms.class.menu%, VinceCmsSonataAdminBundle:Menu ]
        calls:
            - [ setMenuRepository, [ @vince_cms.repository.menu ] ]
            - [ setUploadDir, [ %kernel.upload_dir%, %kernel.web_dir% ] ]

    # Form types
    form.type_extension.filename:
        class: Vince\Bundle\CmsSonataAdminBundle\Form\Extension\FilenameTypeExtension
        tags:
            - { name: form.type_extension, alias: form }

    form.type.metagroup:
        class: Vince\Bundle\CmsSonataAdminBundle\Form\Type\MetaGroupType
        tags:
            - { name: form.type, alias: metagroup }
        calls:
            - [ setMetaRepository, [ @vince_cms.repository.meta ] ]
            - [ setArticleMetaClassName, [ %vince_cms.class.articleMeta% ] ]

    form.type.meta:
        class: Vince\Bundle\CmsSonataAdminBundle\Form\Type\MetaType
        tags:
            - { name: form.type, alias: meta }

    form.type.template:
        class: Vince\Bundle\CmsSonataAdminBundle\Form\Type\TemplateType
        tags:
            - { name: form.type, alias: template }
        calls:
            - [ setTemplateRepository, [ @vince_cms.repository.template ] ]
            - [ setContentClassName, [ %vince_cms.class.content% ] ]

    form.type.area:
        class: Vince\Bundle\CmsSonataAdminBundle\Form\Type\AreaType
        tags:
            - { name: form.type, alias: area }
